---
- name: 'Learn about hosts'
  hosts: all
  gather_facts: true

  tasks:
    - name: Precondition check
      fail:
        msg: 'No os variable set, must be silverblue or workstation' # not required. The customized message used for failing execution. If omitted, fail will simply bail out with a generic message.
      when: os != 'silverblue' and os != 'workstation'
    - name: Group hosts
      group_by:
          key: os_{{ os }}

- name: Workstation | Deploy Playbook
  hosts: os_workstation
  gather_facts: false
  roles:
    - base
    #- podman

- name: Silverblue | Deploy Playbook
  hosts: os_silverblue
  gather_facts: false
  roles:
    - base
    - podman
