# flatpak: {
#   bundles: {
#     gnome: [
#     ],
#     themes: [
#     ],
#     multimedia: [
#     ],
#     messaging: [
#     ],
#     office: [
#     ],
#     gaming: [
#     ],
#     development: [
#     ],
#   }
# }

# ostree: {
#   base: [
#   ],
#   optional: [
#   ]
# }