---

- name: FLATPAK | Install Bundle Gnome
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.gnome }}"

- name: FLATPAK | Install Bundle Theme
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.themes }}"

- name: FLATPAK | Install Bundle Multimedia
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.multimedia }}"

- name: FLATPAK | Install Bundle Messaging
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.messaging }}"

- name: FLATPAK | Install Bundle Office
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.office }}"

- name: FLATPAK | Install Bundle Gaming
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.gaming }}"


- name: FLATPAK | Install Bundle Development
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.development }}"