---
- name: FLATPAK | Enable Flathub repo
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: FLATPAK | Install Bundle Gnome
  become: true
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ flatpak_bundle_gnome if flatpak_bundle_gnome_extra is not defined else (flatpak_bundle_gnome + flatpak_bundle_gnome_extra)}}"
  # TODO: Better check
  ignore_errors: yes
  when:
    flatpak_gnome == True

- name: FLATPAK | Install Bundle Theme
  become: true
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ flatpak_bundle_themes if flatpak_bundle_themes_extra is not defined else (flatpak_bundle_themes + flatpak_bundle_themes_extra)}}"
  # TODO: Better check
  ignore_errors: yes
  when:
    flatpak_themes == True

- name: FLATPAK | Install Bundle Multimedia
  become: true
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ flatpak_bundle_multimedia if flatpak_bundle_multimedia_extra is not defined else (flatpak_bundle_multimedia + flatpak_bundle_multimedia_extra)}}"
  # TODO: Better check
  ignore_errors: yes
  when:
    flatpak_multimedia == True

- name: FLATPAK | Install Bundle Messaging
  become: true
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ flatpak_bundle_messaging if flatpak_bundle_messaging_extra is not defined else (flatpak_bundle_messaging + flatpak_bundle_messaging_extra)}}"
  # TODO: Better check
  ignore_errors: yes
  when:
    flatpak_messaging == True

- name: FLATPAK | Install Bundle Office
  become: true
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ flatpak_bundle_office if flatpak_bundle_office_extra is not defined else (flatpak_bundle_office + flatpak_bundle_office_extra)}}"
  # TODO: Better check
  ignore_errors: yes
  when:
    flatpak_office == True

- name: FLATPAK | Install Bundle Gaming
  become: true
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ flatpak_bundle_gaming if flatpak_bundle_gaming_extra is not defined else (flatpak_bundle_gaming + flatpak_bundle_gaming_extra)}}"
  # TODO: Better check
  ignore_errors: yes
  when:
    flatpak_gaming == True


- name: FLATPAK | Install Bundle Development
  become: true
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ flatpak_bundle_development if flatpak_bundle_development_extra is not defined else (flatpak_bundle_development + flatpak_bundle_development_extra)}}"
  # TODO: Better check
  ignore_errors: yes
  when:
    flatpak_development == True
