---

- name: FLATPAK | Install Bundle Gnome
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.gnome }}"
  # TODO: Better check
  ignore_errors: yes

- name: FLATPAK | Install Bundle Theme
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.themes }}"
  # TODO: Better check
  ignore_errors: yes

- name: FLATPAK | Install Bundle Multimedia
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.multimedia }}"
  # TODO: Better check
  ignore_errors: yes

- name: FLATPAK | Install Bundle Messaging
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.messaging }}"
  # TODO: Better check
  ignore_errors: yes

- name: FLATPAK | Install Bundle Office
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.office }}"
  # TODO: Better check
  ignore_errors: yes

- name: FLATPAK | Install Bundle Gaming
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.gaming }}"
  # TODO: Better check
  ignore_errors: yes


- name: FLATPAK | Install Bundle Development
  flatpak:
    name: "{{ item }}"
    remote: flathub
    method: system
    state: present
  with_items: "{{ vars.flatpak.bundles.development }}"
  # TODO: Better check
  ignore_errors: yes
