---
- name: BASE | Enable RPM Fusion Repo
  include: repo.rpmfusion.yml
  tags:
    - base_rpmfusion
  when:
    base_rpmfusion == true

- name: BASE | flatpaks
  include: flatpaks.yml
  tags:
    - base_flatpaks
  when:
    base_flatpaks == true

- name: BASE | lutris
  include: lutris.yml
  tags:
    - base_lutris
  when:
    base_lutris.enable == true and base_lutris.flatpak == false

- name: BASE | lutris - flatpak
  include: lutris.flatpak.yml
  tags:
    - base_lutris_flatpak
  when:
    base_lutris.enable == true and base_lutris.flatpak == true

- name: BASE | lutris - postconfig
  include: lutris.postconfig.yml
  tags:
    - base_lutris_postconfig
  when:
    base_lutris.enable == true and base_lutris.postconfig == true

- name: BASE | nvidia
  include: nvidia.yml
  tags:
    - base_nvidia
  when:
    base_nvidia == true

- name: BASE | configure
  include: configure.yml
  tags:
    - base_configure
  when:
    base_configure.enable == true

- name: BASE | rpm-ostree
  include: rpm-ostree.yml
  tags:
    - base_ostree
  when:
    os == 'silverblue'

- name: BASE | dnf workstation
  include: workstation.yml
  tags:
    - base_workstation
  when:
    os == 'workstation'

- name: BASE | Custom Kernel Surface
  include: surface.yml
  tags:
    - base_surface
  when: base_surface == true

- name: BASE | Dconf Settings
  include: dconf.yml
  tags:
    - base_dconf
  when:
    base_dconf == true
