---

- name: REPO | Create RPM Fusion Free
  blockinfile:
    path: /etc/yum.repos.d/rpmfusion-free.repo
    create: true
    block: |
      name=RPM Fusion for Fedora $releasever - Free
      #REPOurl=http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$REPOarch/os/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$REPOarch
      enabled=1
      metadata_expire=14d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

      [rpmfusion-free-debuginfo]
      name=RPM Fusion for Fedora $releasever - Free - Debug
      #REPOurl=http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$REPOarch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-debug-$releasever&arch=$REPOarch
      enabled=0
      metadata_expire=7d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

      [rpmfusion-free-source]
      name=RPM Fusion for Fedora $releasever - Free - Source
      #REPOurl=http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/source/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-source-$releasever&arch=$REPOarch
      enabled=0
      metadata_expire=7d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

- name: REPO | Create RPM Fusion Free Updates
  blockinfile:
    path: /etc/yum.repos.d/rpmfusion-free-updates.repo
    create: true
    block: |
      name=RPM Fusion for Fedora $releasever - Free - Updates
      #REPOurl=http://download1.rpmfusion.org/free/fedora/updates/$releasever/$REPOarch/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$REPOarch
      enabled=1
      enabled_metadata=1
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

      [rpmfusion-free-updates-debuginfo]
      name=RPM Fusion for Fedora $releasever - Free - Updates Debug
      #REPOurl=http://download1.rpmfusion.org/free/fedora/updates/$releasever/$REPOarch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-debug-$releasever&arch=$REPOarch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

      [rpmfusion-free-updates-source]
      name=RPM Fusion for Fedora $releasever - Free - Updates Source
      #REPOurl=http://download1.rpmfusion.org/free/fedora/updates/$releasever/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-source-$releasever&arch=$REPOarch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever


- name: REPO | Create RPM Fusion Free Updates Testing
  blockinfile:
    path: /etc/yum.repos.d/rpmfusion-free-updates-testing.repo
    create: true
    block: |
      name=RPM Fusion for Fedora $releasever - Free - Test Updates
      #REPOurl=http://download1.rpmfusion.org/free/fedora/updates/testing/$releasever/$REPOarch/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-testing-$releasever&arch=$REPOarch
      enabled=0
      enabled_metadata=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

      [rpmfusion-free-updates-testing-debuginfo]
      name=RPM Fusion for Fedora $releasever - Free - Test Updates Debug
      #REPOurl=http://download1.rpmfusion.org/free/fedora/updates/testing/$releasever/$REPOarch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-testing-debug-$releasever&arch=$REPOarch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

      [rpmfusion-free-updates-testing-source]
      name=RPM Fusion for Fedora $releasever - Free - Test Updates Source
      #REPOurl=http://download1.rpmfusion.org/free/fedora/updates/testing/$releasever/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-testing-source-$releasever&arch=$REPOarch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever


- name: REPO | Create RPM Fusion NonFree
  blockinfile:
    path: /etc/yum.repos.d/rpmfusion-nonfree.repo
    create: true
    block: |
      [rpmfusion-nonfree]
      name=RPM Fusion for Fedora $releasever - Nonfree
      #REPOurl=http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$REPOarch/os/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$REPOarch
      enabled=1
      enabled_metadata=1
      metadata_expire=14d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

      [rpmfusion-nonfree-debuginfo]
      name=RPM Fusion for Fedora $releasever - Nonfree - Debug
      #REPOurl=http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$REPOarch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-debug-$releasever&arch=$REPOarch
      enabled=0
      metadata_expire=7d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

      [rpmfusion-nonfree-source]
      name=RPM Fusion for Fedora $releasever - Nonfree - Source
      #REPOurl=http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/source/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-source-$releasever&arch=$REPOarch
      enabled=0
      metadata_expire=7d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

- name: REPO | Create RPM Fusion NonFree Updates
  blockinfile:
    path: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
    create: true
    block: |
      [rpmfusion-nonfree-updates]
      name=RPM Fusion for Fedora $releasever - Nonfree - Updates
      #REPOurl=http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/$REPOarch/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$REPOarch
      enabled=1
      enabled_metadata=1
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

      [rpmfusion-nonfree-updates-debuginfo]
      name=RPM Fusion for Fedora $releasever - Nonfree - Updates Debug
      #REPOurl=http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/$REPOarch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-debug-$releasever&arch=$REPOarch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

      [rpmfusion-nonfree-updates-source]
      name=RPM Fusion for Fedora $releasever - Nonfree - Updates Source
      #REPOurl=http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-source-$releasever&arch=$REPOarch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

- name: REPO | Create RPM Fusion NonFree Updates Testing
  blockinfile:
    path: /etc/yum.repos.d/rpmfusion-nonfree-updates-testing.repo
    create: true
    block: |
      [rpmfusion-nonfree-updates-testing]
      name=RPM Fusion for Fedora $releasever - Nonfree - Test Updates
      #REPOurl=http://download1.rpmfusion.org/nonfree/fedora/updates/testing/$releasever/$REPOarch/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-testing-$releasever&arch=$REPOarch
      enabled=0
      enabled_metadata=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

      [rpmfusion-nonfree-updates-testing-debuginfo]
      name=RPM Fusion for Fedora $releasever - Nonfree - Test Updates Debug
      #REPOurl=http://download1.rpmfusion.org/nonfree/fedora/updates/testing/$releasever/$REPOarch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-testing-debug-$releasever&arch=$REPOarch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

      [rpmfusion-nonfree-updates-testing-source]
      name=RPM Fusion for Fedora $releasever - Nonfree - Test Updates Source
      #REPOurl=http://download1.rpmfusion.org/nonfree/fedora/updates/testing/$releasever/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-testing-source-$releasever&arch=$REPOarch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever