---

- name: REPO | Install RPM Fusion (via ostree)
  shell: |
     sudo rpm-ostree install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm 
  when:
    os == 'silverblue'
  # TODO: Better check
  ignore_errors: yes

- name: REPO | Install RPM Fusion (via dnf)
  shell: |
    sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  when:
    os == 'workstation'