---
- name: OSTREE | Install Base
  command: "rpm-ostree install {{  vars['base']['ostree']['base'] }}"

- name: OSTREE | Install Optional
  command: "rpm-ostree install {{  vars['base']['ostree']['optional'] }}"