---
- name: OSTREE | Install Base
  command: "rpm-ostree install {{ item }}"
  with_items: "{{ vars.ostree.base }}"
  # TODO: Better check
  ignore_errors: yes


- name: OSTREE | Install Optional
  command: rpm-ostree install {{ item }}
  with_items: "{{ vars.ostree.optional }}"
  # TODO: Better check
  ignore_errors: yes
