---
- name: Workstation | Install base packages
  become: true
  package:
    name: "{{ item }}"  
    state: present
  with_items:
    - "{{ basepkg }}" 
    
- name: Workstation | Install optional packages
  become: true
  package:
    name: "{{ item }}"  
    state: present
  with_items:
    - "{{ optpkg }}"  